-- Run this in the Supabase SQL editor, after 0001_contact_messages.sql.
-- Creates the products/categories tables that will back the storefront
-- catalog (replacing the static src/data/products.json) plus RLS so:
--   - anyone (anon + authenticated) can read the catalog
--   - only logged-in admin accounts (authenticated) can insert new products

create table if not exists public.categories (
  id bigint primary key,
  name text not null,
  slug text not null unique
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text not null default '',
  sku text not null default '',
  price numeric(10, 2) not null,
  currency text not null default 'usd',
  in_stock boolean not null default true,
  image text,
  category_ids bigint[] not null default '{}',
  variants jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.categories enable row level security;
alter table public.products enable row level security;

create policy "categories_public_read"
  on public.categories
  for select
  using (true);

create policy "products_public_read"
  on public.products
  for select
  using (true);

create policy "products_authenticated_insert"
  on public.products
  for insert
  to authenticated
  with check (true);
