-- Run this in the Supabase SQL editor, after 0005_products_update_delete.sql.
-- Backs the homepage FAQ accordion (previously hardcoded in page.tsx) with
-- an admin-editable table. Seeded with the 5 existing hardcoded entries so
-- the homepage looks the same immediately after this runs.

create table if not exists public.faqs (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  created_at timestamptz not null default now()
);

alter table public.faqs enable row level security;

create policy "faqs_public_read"
  on public.faqs
  for select
  using (true);

create policy "faqs_authenticated_insert"
  on public.faqs
  for insert
  to authenticated
  with check (true);

create policy "faqs_authenticated_update"
  on public.faqs
  for update
  to authenticated
  using (true)
  with check (true);

create policy "faqs_authenticated_delete"
  on public.faqs
  for delete
  to authenticated
  using (true);

insert into public.faqs (question, answer) values
  ('Are your peptides real and authentic?', 'Yes — we are a factory-direct supplier with stable production and large inventory. All products are manufactured under strict quality standards, and COAs (Certificates of Analysis) are available for verification.'),
  ('What if there is a problem with my order?', 'Inspect your order on arrival. If an item is defective, damaged, or incorrect, contact our support team and we''ll handle a refund or replacement directly — no need to push the issue to your own customers.'),
  ('Why are your prices lower than other companies?', 'We sell factory-direct with no reseller layers, no brand premiums, and no stacked margins. Pricing reflects production, packaging, and logistics — not retail markup.'),
  ('Do you offer bulk discounts?', 'Yes. Kit-based wholesale pricing is available for distributors and repeat buyers, with priority access for long-term partners. Contact support for a bulk quote.'),
  ('What payment methods do you accept?', 'We currently accept Bitcoin. Full payment instructions are provided at checkout.'),
  ('How long does shipping take?', 'China warehouse: 8-15 business days worldwide. USA warehouses: 3-5 business days within the US. Canada warehouse: 3-6 business days within Canada.'),
  ('Do I need to pay customs or taxes?', 'No. All China warehouse shipments are DDP (Delivered Duty Paid) — duties and taxes are prepaid, so there are no additional import fees on delivery.'),
  ('Do you ship to my country?', 'The China warehouse ships worldwide. Our USA and Canada warehouses ship domestically only, within the US and Canada respectively.'),
  ('When will my order be shipped?', 'Orders are processed Monday-Friday, and a tracking number is emailed as soon as your order ships.'),
  ('Why is my tracking not updating?', 'Tracking can take 24-48 hours to register after a label is created, and may pause briefly during customs clearance. If it hasn''t updated after 5 business days, contact support and we''ll look into it.'),
  ('How should peptides be stored?', 'Lyophilized (freeze-dried) peptides should be stored frozen and protected from light until reconstitution. Once reconstituted, store refrigerated and use within the timeframe recommended for that specific peptide. Refer to each product page for compound-specific guidance.');
