-- Run this in the Supabase SQL editor, after 0006_faqs.sql.
-- Backs the homepage "What our customers say" section and the
-- dedicated /testimonials page.

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  stars smallint not null default 5 check (stars between 1 and 5),
  quote text not null,
  created_at timestamptz not null default now()
);

alter table public.testimonials enable row level security;

create policy "testimonials_public_read"
  on public.testimonials
  for select
  using (true);

create policy "testimonials_authenticated_insert"
  on public.testimonials
  for insert
  to authenticated
  with check (true);

create policy "testimonials_authenticated_update"
  on public.testimonials
  for update
  to authenticated
  using (true)
  with check (true);

create policy "testimonials_authenticated_delete"
  on public.testimonials
  for delete
  to authenticated
  using (true);
