-- Run this in the Supabase SQL editor, after 0007_testimonials.sql.
-- Backs the admin blog editor and the public /blog + /blog/[slug] pages.

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null default '',
  content text not null default '',
  cover_image text,
  meta_description text not null default '',
  published boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.blog_posts enable row level security;

-- Public (anon) visitors — and generateStaticParams at build time, which
-- reads through the same anon key — only ever see published posts. Drafts
-- stay invisible until the admin publishes them, not just hidden by the
-- app's own query filter.
create policy "blog_posts_public_read"
  on public.blog_posts
  for select
  to anon
  using (published = true);

-- Logged-in admin sees everything, published or not (needed for the admin
-- list/edit pages).
create policy "blog_posts_authenticated_read"
  on public.blog_posts
  for select
  to authenticated
  using (true);

create policy "blog_posts_authenticated_insert"
  on public.blog_posts
  for insert
  to authenticated
  with check (true);

create policy "blog_posts_authenticated_update"
  on public.blog_posts
  for update
  to authenticated
  using (true)
  with check (true);

create policy "blog_posts_authenticated_delete"
  on public.blog_posts
  for delete
  to authenticated
  using (true);
